### ISSUE TITLE
opsys specific?

### ISSUE THREAD

**Issue by jimlynnjulian** [cweiske/tmdb2mkvtags#1]
Can I assume this is for Linux and not Windows?

**Comment by cweiske** [comment]
I only tested it on Linux, but it should work on windows as well.

**Comment by jimlynnjulian** [comment]
Not working.
I tried PHP8 at first, then an older version, PHP7.4.33.
I keep getting the same errors.
My tmdb key page has API key (v3) and Read Access Key (v4). I used the Read Access Key (v4), the one with 230 characters.

===============================================================================
php tmdb2mkvtags.php de "James Bond"

Warning: file_get_contents(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP? in C:\Users\jimly\Downloads\__video mkv\MKV and tags\tmdb2mkvtags-master\tmdb2mkvtags.php on line 295

Warning: file_get_contents(https://api.themoviedb.org//3/search/movie?query=James+Bond&language=de&include_adult=1): failed to open stream: No such file or directory in C:\Users\jimly\Downloads\__video mkv\MKV and tags\tmdb2mkvtags-master\tmdb2mkvtags.php on line 295

Fatal error: Uncaught Exception: Error querying API:  in C:\Users\jimly\Downloads\__video mkv\MKV and tags\tmdb2mkvtags-master\tmdb2mkvtags.php:305
Stack trace:
#0 C:\Users\jimly\Downloads\__video mkv\MKV and tags\tmdb2mkvtags-master\tmdb2mkvtags.php(56): queryTmdb('/3/search/movie...')
#1 {main}
  thrown in C:\Users\jimly\Downloads\__video mkv\MKV and tags\tmdb2mkvtags-master\tmdb2mkvtags.php on line 305

===============================================================================

**Comment by jimlynnjulian** [comment]
...just noticed the "https wrapper" issue. Checking that out.
Did not seem to make a difference.

**Comment by cweiske** [comment]
See https://cweiske.de/tagebuch/php-error-https-wrapper.htm
Comment with the error output when the https error is gone.

**Comment by jimlynnjulian** [comment]
Hello again,

   I did as you requested but the dll is not accessible. I uncommented an adjacent entry "openssl" and that was not locatable either. I checked the Path variable for user and system and both contain the PHP folder. The dlls are in the 'ext' folder, contrary to what the error message states.


==============================================================
php tmdb2mkvtags.php de "James Bond"
PHP Warning:  PHP Startup: Unable to load dynamic library 'openssl' (tried: C:\php\ext\openssl (The specified module could not be found.), C:\php\ext\php_openssl.dll (The specified module could not be found.)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_openssl.dll' (tried: C:\php\ext\php_openssl.dll (The specified module could not be found.), C:\php\ext\php_php_openssl.dll.dll (The specified module could not be found.)) in Unknown on line 0
PHP Warning:  file_get_contents(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP? in C:\Users\jimly\Downloads\__video mkv\MKV and tags\tmdb2mkvtags-master\tmdb2mkvtags.php on line 295
PHP Warning:  file_get_contents(https://api.themoviedb.org//3/search/movie?query=James+Bond&language=de&include_adult=1): failed to open stream: No such file or directory in C:\Users\jimly\Downloads\__video mkv\MKV and tags\tmdb2mkvtags-master\tmdb2mkvtags.php on line 295
PHP Notice:  Undefined variable: http_response_header in C:\Users\jimly\Downloads\__video mkv\MKV and tags\tmdb2mkvtags-master\tmdb2mkvtags.php on line 296
PHP Notice:  Trying to access array offset on value of type null in C:\Users\jimly\Downloads\__video mkv\MKV and tags\tmdb2mkvtags-master\tmdb2mkvtags.php on line 296
PHP Notice:  Undefined offset: 1 in C:\Users\jimly\Downloads\__video mkv\MKV and tags\tmdb2mkvtags-master\tmdb2mkvtags.php on line 296
PHP Fatal error:  Uncaught Exception: Error querying API:  in C:\Users\jimly\Downloads\__video mkv\MKV and tags\tmdb2mkvtags-master\tmdb2mkvtags.php:305
Stack trace:
#0 C:\Users\jimly\Downloads\__video mkv\MKV and tags\tmdb2mkvtags-master\tmdb2mkvtags.php(56): queryTmdb()
#1 {main}
  thrown in C:\Users\jimly\Downloads\__video mkv\MKV and tags\tmdb2mkvtags-master\tmdb2mkvtags.php on line 305

===============================================================

**Comment by cweiske** [comment]
Closing since this is not a problem with tmdb2mkvtags but with your PHP setup.

**Comment by jimlynnjulian** [comment]
Thanks for your time. I made two additions to the .ini and the programs runs as advertised.
For future readers:
1. Uncommented ";extension=php_openssl.dll"
2. Added "extension_dir = "ext" "
3. Added complete PHP folder path to the PATH variable.
Thanks again.
